base_local_planner: potbot_nav/PotbotLocalPlanner

PotbotLocalPlanner:
  controller_name: potbot_nav/PurePursuit
  
  controller:
    normalize: true
    max_linear_velocity: 0.2
    max_angular_velocity: 1.5
    distance_to_lookahead_point: 0.45
    stop_margin_distance: 0.1

