obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.3,-0.2],[-0.3,0.2],[0.125,0.2],[0.125,-0.2]]
#robot_radius: 0.17

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan depth_cloud
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
depth_cloud: {sensor_frame: robot_5/camera_points_frame, data_type: PointCloud2, topic: /robot_5/camera/points/data_raw, marking: true, clearing: true}
