map_update_interval: 0.1  #マップを更新する間隔の時間 (秒単位)。この数値を下げると、占有グリッドの更新頻度が高くなりますが、計算負荷が高くなります。( float、デフォルト: 5.0)
maxUrange: 20.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 50
srr: 0.1  #平行移動の関数としての平行移動におけるオドメトリ誤差(rho/rho)( float、デフォルト: 0.1)
srt: 0.2  #回転の関数としての平行移動におけるオドメトリ誤差(rho/theta)( float、デフォルト: 0.2)
str: 0.1  #平行移動の関数としての回転時のオドメトリ誤差 (theta/rho)( float、デフォルト: 0.1)
stt: 0.2  #回転の関数としての回転時のオドメトリ誤差 (theta/theta)( float、デフォルト: 0.2)
linearUpdate: 1.0
angularUpdate: 0.2
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 100
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
