markers: 
  - {id: 0, frame_id: "map", pose: {x: 1.64, y: -0.42, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}}
  - {id: 1, frame_id: "marker_0", pose: {x: 2.0, y: 1.03, z: 0.28, roll: 0.0, pitch: 0.0, yaw: 3.14}}
  - {id: 2, frame_id: "marker_0", pose: {x: 3.0, y: -1.1, z: 0.28, roll: 0.0, pitch: 0.0, yaw: 3.14}}
  - {id: 3, frame_id: "marker_0", pose: {x: 4.0, y: 1.03, z: 0.28, roll: 0.0, pitch: 0.0, yaw: 3.14}}
  - {id: 4, frame_id: "marker_0", pose: {x: 5.0, y: -1.1, z: 0.28, roll: 0.0, pitch: 0.0, yaw: 3.14}}
  - {id: 5, frame_id: "marker_0", pose: {x: 6.0, y: 1.03, z: 0.28, roll: 0.0, pitch: 0.0, yaw: 3.14}}
  - {id: 6, frame_id: "marker_0", pose: {x: 7.0, y: -1.1, z: 0.28, roll: 0.0, pitch: 0.0, yaw: 3.14}}